name: FTP Deploy

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        remote-dir: "plateaustate.gov.ng" # The remote directory to upload to
